server:
  port: 3344
spring:
  application:
    name: cloud-config-center3344
  cloud:
    config:
      server:
        git:
          # Github上面git仓库的地址
          uri: https://github.com/yyz159756/springcloud-config.git
          # 搜索的目录
          search-paths:
            - springcloud-config
      # 分支
      label: master

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka